# This YAML file will create 4 containers:
#  - MongoDB
#  - RSS-Bridge
#  - RSSHub
#  - RSS Telegram bot itself
# and a bridged network connecting them.
# First 3 will have their used ports mapped to host, but it's used only for debugging.
# External access through host isn't needed, since bot accesses containers directly.
# Each container has "unless-stopped" restart policy, so they should start when host reboots.
# Techincally only bot and MongoDB is needed, however this serves as a nice deployment example.

x-service-defaults: &service-defaults
  restart: unless-stopped

x-volume-timezone: &volume-timezone
  /etc/timezone:/etc/timezone:ro

x-volume-localtime: &volume-localtime
  /etc/localtime:/etc/localtime:ro

services:
  rss-bridge:
    << : *service-defaults
    image: rssbridge/rss-bridge:latest
    container_name: rss-reader-rss-bridge
    # Mapping "/config" allows for passing extra configuration to RSS-Bridge.
    volumes:
      - ./rss-bridge/config/custom/config.ini.php:/config/custom/config.ini.php
      - ./rss-bridge/custom_bridges/reddit-oauth/RedditBridge.php:/config/custom/RedditBridge.php:ro
      - ./rss-bridge/custom_bridges/youtube-shorts/YoutubeShortsBridge.php:/config/custom/YoutubeShortsBridge.php:ro
      - *volume-timezone
      - *volume-localtime
    ports:
      - 5001:80
    profiles:
      - rss-bridge

  rss-hub:
    << : *service-defaults
    image: diygod/rsshub:latest
    container_name: rss-reader-rss-hub
    volumes:
      - *volume-timezone
      - *volume-localtime
    ports:
      - 5002:1200
    # "./rss-hub/.env" can be used to further configure RSSHub.
    env_file:
      - ./rss-hub/.env
    profiles:
      - rss-hub

  mongo-db:
    << : *service-defaults
    image: mongo
    container_name: rss-reader-mongo-db
    # Mounting "/data/db" means, that this MongoDB will actually store its data on host,
    # rather than on container itself.
    volumes:
      - ./mongo-db/data:/data/db
      - *volume-timezone
      - *volume-localtime
    ports:
      - 5003:27017

  telegram-bot:
    << : *service-defaults
    image: rss-reader-telegram-bot:latest
    build: ./telegram-bot/source-code/
    container_name: rss-reader-telegram-bot
    # Mounted "/config" is used for passing RSS links to the bot.
    # This way there's no need to rebuild the image when links are changed.
    # Additionally that's where bot internal logs will be stored, so they are accessible
    # without getting into the container itself.
    volumes:
      - ./telegram-bot/config:/config
      - *volume-timezone
      - *volume-localtime
    # Pointing the custom YAML configuration file to mounted volume.
    # "telegram-bot/config/custom_settings.yml" can be used for further customization
    # of the bot parameters without the need of rebuilding the whole image.
    environment:
      - CUSTOM_SETTINGS_PATH=/config/custom_settings.yml

  # Additional modules.
  rss-bridge-reddit-filter:
    << : *service-defaults
    image: rss-bridge-reddit-filter:latest
    container_name: rss-reader-rss-bridge-reddit-filter
    build: ./rss-bridge-reddit-filter/
    volumes:
      - *volume-timezone
      - *volume-localtime
    ports:
      - 5004:8000
    environment:
      - UVICORN_PORT=8000
      - RSS_BRIDGE_URL=http://rss-bridge:80/
    profiles:
      - rss-bridge

  rss-bridge-ytdlp-wrapper:
    << : *service-defaults
    image: rss-bridge-ytdlp-wrapper:latest
    container_name: rss-reader-rss-bridge-ytdlp-wrapper
    build: ./rss-bridge-ytdlp-wrapper/
    volumes:
      - *volume-timezone
      - *volume-localtime
    ports:
      - 5005:8000
    environment:
      - UVICORN_PORT=8000
      - RSS_BRIDGE_URL=http://rss-bridge:80/
      - DURATION_MAX=120
      - FORMAT=bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best
      - FORMAT_SORT=codec:h264:aac
    profiles:
      - rss-bridge

networks:
  default:
    name: rss-reader-network
    driver: bridge
